<?php
/**
 * @file
 * Code for the Commerce Affiliates Feature feature.
 */

include_once 'commerce_affiliates_feature.features.inc';

function commerce_affiliates_feature_permission() {
    return array(
        'access to affiliate feature' => array(
            'title' => t('Access to Affiliate Feature'),
            'description' => t('Allow user to collect commission for referring users to your site.'),
        ),
    );
}

function commerce_affiliates_feature_views_post_build(&$view) {
    if ($view->name == 'affiliates_activity') {
        $view->build_info['breadcrumb'] = array();
    }
}
